name: Update Bing Image of the Day

on:
  schedule:
    - cron: "0 * * * *" # This will run every hour
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Bing Image of the Day
        run: |
          echo "Fetching the Bing image of the day..."
          image_url=$(curl -s 'https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US' | jq -r '.images[0].url')
          full_image_url="https://www.bing.com$image_url"
          echo "Downloading image from $full_image_url"
          curl -o new-image-of-the-day.jpg "$full_image_url"

      - name: Compare Image
        run: |
          if [ -f image-of-the-day.jpg ]; then
            if cmp -s new-image-of-the-day.jpg image-of-the-day.jpg; then
              echo "Images are the same. Skipping commit."
              echo "commit_needed=false" >> $GITHUB_ENV
            else
              echo "Images are different. Commit is needed."
              echo "commit_needed=true" >> $GITHUB_ENV
            fi
          else
            echo "No previous image found. Commit is needed."
            echo "commit_needed=true" >> $GITHUB_ENV
          fi
        id: compare_image

      - name: Commit and Push Changes
        if: env.commit_needed == 'true' # Only commit if the previous step determined a commit is needed
        run: |
          mkdir -p iotd
          current_date=$(date +%F)
          
          # Move the new image and save it in the iotd folder with the date
          mv new-image-of-the-day.jpg image-of-the-day.jpg
          cp image-of-the-day.jpg iotd/$current_date.jpg

          # Commit the changes
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add *
          git commit -m "Update image-of-the-day and archive $current_date"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
